# Ansible playbook for webserver
---
- hosts: webserver
  become: true
  become_method: sudo
  tasks:
    - name: Build docker image from Dockerfile
      docker_image:
        build:
          path: ./webserver
          pull: no
        source: build
        state: present
    - name: Running the container
      docker_container:
        name: nginx
        image: web
        ports: 80:8080
        state: running
      register: web1
    - name: Check if Nginx container is running
      shell: docker ps