# Ansible playbook for webserver
---
- hosts: localhost
  become: true
  tasks: 
    - name: Build docker image from Dockerfile
      docker_image:
        build:
          path: ./webserver
          pull: no
        name: webserver
        source: build
      tags: build
    - name: Running the container
      docker_container:
        name: webserver
        image: webserver
        ports: 80:80
        pull: no
      tags: run
